import { z } from 'zod';
import {
  BotTestDirectiveSchema,
  type BotTestDirective,
  type BotTestDirectiveMode,
  type BotTestDirectivePriority,
  type BotTestDirectiveType
} from '../types/botTestDirective';
import { ResourceWeightSchema } from '../types/bot';
import { SessionLabelSchema } from '../types/sessionBundle';

export const FocusedTestTemplateIdSchema = z.enum([
  'test-crafting-system',
  'test-building-system',
  'test-inventory-integrity',
  'test-save-and-reload',
  'test-main-menu-and-settings',
  'test-controller-inputs',
  'test-mobile-controls',
  'test-resolution-and-ui-scaling',
  'test-npc-navigation',
  'test-boss-encounter',
  'test-procedural-world-generation',
  'test-day-night-and-weather',
  'test-loading-transitions',
  'test-long-term-memory-use',
  'reproduce-selected-issue'
]);

const FocusedDirectiveDefaultsSchema = z.object({
  name: z.string().min(1),
  description: z.string().min(1),
  directiveType: z.enum([
    'action',
    'feature',
    'scene',
    'area',
    'ui-flow',
    'game-state',
    'issue-reproduction',
    'sequence',
    'freeform'
  ]),
  directiveMode: z.enum([
    'influence',
    'focus',
    'force-next-valid-action',
    'repeat-until-condition',
    'guided-sequence'
  ]),
  priority: z.enum(['low', 'normal', 'high', 'urgent']),
  actionKeywords: z.array(z.string().min(1)).min(1),
  avoidedActionKeywords: z.array(z.string().min(1)).default([]),
  targetFeature: z.string().min(1).optional(),
  successConditions: z.array(z.string().min(1)).min(1),
  maxAttempts: z.number().int().min(1).max(10),
  repeatUntilSuccess: z.boolean(),
  manualSuccessConfirmation: z.boolean().default(false)
});

export const FocusedTestTemplateSchema = z.object({
  id: FocusedTestTemplateIdSchema,
  name: z.string().min(1),
  botProfileId: z.string().min(1),
  actionCount: z.number().int().min(10).max(60),
  runtimeMinutes: z.number().int().min(5).max(30),
  actionDelayMs: z.number().int().min(500).max(1_000),
  saveScreenshots: z.boolean(),
  saveStateSnapshots: z.boolean(),
  resourceWeight: ResourceWeightSchema,
  sessionLabel: SessionLabelSchema,
  backgroundPreferred: z.boolean(),
  whatItDoes: z.string().min(20),
  requiredCapabilities: z.array(z.string().min(1)).min(1),
  limitations: z.string().min(20),
  beginnerRecommendation: z.string().min(20),
  directive: FocusedDirectiveDefaultsSchema
});

export type FocusedTestTemplateId = z.infer<typeof FocusedTestTemplateIdSchema>;
export type FocusedTestTemplate = z.infer<typeof FocusedTestTemplateSchema>;

const focusedTemplateInput = [
  {
    id: 'test-crafting-system',
    name: 'Test Crafting System',
    botProfileId: 'crafting-recipe-tester-bot',
    actionCount: 30,
    runtimeMinutes: 15,
    actionDelayMs: 650,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests valid and invalid recipes, ingredient changes, repeated crafting, cancellation, and output integrity.',
    requiredCapabilities: ['crafting actions', 'inventory and recipe state'],
    limitations: 'Without readable inventory state, item loss or duplication may require manual screenshot review.',
    beginnerRecommendation: 'Start with one disposable save and confirm that one normal recipe works before running this focused test.',
    directive: {
      name: 'Test crafting recipes and output integrity',
      description: 'Open crafting interfaces, try valid and invalid recipes, remove ingredients, craft multiple outputs, and check for item loss or duplication.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['open-crafting', 'select-recipe', 'add-ingredient', 'remove-ingredient', 'craft', 'craft-multiple', 'cancel-craft'],
      avoidedActionKeywords: ['delete-save'],
      targetFeature: 'crafting',
      successConditions: ['Crafting actions complete and inventory output remains consistent.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'test-building-system',
    name: 'Test Building System',
    botProfileId: 'building-destruction-tester-bot',
    actionCount: 30,
    runtimeMinutes: 15,
    actionDelayMs: 700,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests placement, invalid placement, rotation, overlap rules, removal, destruction, limits, and persistence.',
    requiredCapabilities: ['building controls', 'object placement state or screenshots'],
    limitations: 'Use a disposable world because placement and destruction can permanently change the test save.',
    beginnerRecommendation: 'Map place, rotate, remove, and destroy actions, then begin with one small empty building area.',
    directive: {
      name: 'Test building placement and destruction',
      description: 'Place valid and invalid objects, rotate them, try overlaps, remove and destroy them, and check that world state stays correct.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['place-object', 'invalid-placement', 'rotate-object', 'remove-object', 'destroy-object', 'save-world', 'load-world'],
      avoidedActionKeywords: ['delete-world'],
      targetFeature: 'building',
      successConditions: ['Valid objects persist and invalid or overlapping placements are rejected safely.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'test-inventory-integrity',
    name: 'Test Inventory Integrity',
    botProfileId: 'inventory-stress-tester-bot',
    actionCount: 30,
    runtimeMinutes: 15,
    actionDelayMs: 600,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests moving, sorting, stacking, equipping, using, and overflowing items without losing or duplicating them.',
    requiredCapabilities: ['inventory actions', 'inventory state or clear screenshots'],
    limitations: 'A black-box adapter may perform item actions but cannot always prove exact quantities automatically.',
    beginnerRecommendation: 'Use a copied save with several harmless items and leave valuable production saves outside the test.',
    directive: {
      name: 'Test inventory item integrity',
      description: 'Open inventory, sort and move items, stack and split them, equip and unequip them, and check that quantities stay correct.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['open-inventory', 'sort-inventory', 'move-item', 'stack-item', 'split-stack', 'equip-item', 'unequip-item', 'use-item'],
      avoidedActionKeywords: ['discard-all'],
      targetFeature: 'inventory',
      successConditions: ['Inventory quantities and item identities remain correct after at least three item operations.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'test-save-and-reload',
    name: 'Test Save And Reload',
    botProfileId: 'save-load-tester-bot',
    actionCount: 24,
    runtimeMinutes: 15,
    actionDelayMs: 750,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Saves known progress, changes state, reloads the save or checkpoint, and checks that earlier state returns.',
    requiredCapabilities: ['save and load actions', 'save isolation', 'readable progress state'],
    limitations: 'Shared or production saves can be overwritten, so save isolation or a disposable test profile is strongly recommended.',
    beginnerRecommendation: 'Use one isolated copy of a test save and confirm manual save and load once before automation.',
    directive: {
      name: 'Test save and reload integrity',
      description: 'Save the game, change progress or inventory, reload the save, and verify that the saved state returns without corruption.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['save-game', 'change-state', 'load-save', 'load-checkpoint', 'reload-scene'],
      avoidedActionKeywords: ['delete-save'],
      targetFeature: 'save-load',
      successConditions: ['The saved state reloads without missing, duplicated, or corrupted progress.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'test-main-menu-and-settings',
    name: 'Test Main Menu And Settings',
    botProfileId: 'settings-configuration-tester-bot',
    actionCount: 25,
    runtimeMinutes: 12,
    actionDelayMs: 650,
    saveScreenshots: true,
    saveStateSnapshots: false,
    resourceWeight: 'light',
    sessionLabel: 'UI Flow',
    backgroundPreferred: false,
    whatItDoes: 'Tests opening menus, changing settings, applying, cancelling, resetting defaults, and returning to gameplay.',
    requiredCapabilities: ['UI or mapped input actions', 'UI state or screenshots'],
    limitations: 'Visual-only testing may need a person to confirm text, contrast, or subtle setting changes.',
    beginnerRecommendation: 'Choose reversible settings and keep the game visible so the first menu journey can be reviewed.',
    directive: {
      name: 'Test the main menu and settings',
      description: 'Open the main menu and settings, change reversible options, apply and cancel changes, reset defaults, and close every menu.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['open-menu', 'open-settings', 'change-setting', 'apply-settings', 'cancel', 'reset-defaults', 'close-menu'],
      avoidedActionKeywords: ['quit-game', 'delete-save'],
      targetFeature: 'main-menu-settings',
      successConditions: ['Menus accept input, reversible settings apply or cancel correctly, and the game returns from the menu.'],
      maxAttempts: 3,
      repeatUntilSuccess: false,
      manualSuccessConfirmation: true
    }
  },
  {
    id: 'test-controller-inputs',
    name: 'Test Controller Inputs',
    botProfileId: 'controller-gamepad-tester-bot',
    actionCount: 25,
    runtimeMinutes: 12,
    actionDelayMs: 650,
    saveScreenshots: true,
    saveStateSnapshots: false,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests mapped sticks, triggers, buttons, navigation, reconnect behavior, and controller switching.',
    requiredCapabilities: ['gamepad input mappings', 'gamepad-capable adapter or instrumented actions'],
    limitations: 'The test is unavailable when the selected adapter cannot report or simulate safe gamepad input.',
    beginnerRecommendation: 'Confirm one harmless controller button in the profile test before applying the full focused test.',
    directive: {
      name: 'Test mapped controller inputs',
      description: 'Try mapped buttons, sticks, triggers, menu navigation, reconnect behavior, and controller switching.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['gamepad-button', 'gamepad-stick', 'gamepad-trigger', 'controller-menu', 'controller-reconnect', 'controller-switch'],
      avoidedActionKeywords: [],
      targetFeature: 'controller-input',
      successConditions: ['Every reported controller action produces the expected game response.'],
      maxAttempts: 3,
      repeatUntilSuccess: false,
      manualSuccessConfirmation: true
    }
  },
  {
    id: 'test-mobile-controls',
    name: 'Test Mobile Controls',
    botProfileId: 'touch-mobile-controls-tester-bot',
    actionCount: 25,
    runtimeMinutes: 12,
    actionDelayMs: 650,
    saveScreenshots: true,
    saveStateSnapshots: false,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests taps, long presses, swipes, virtual controls, orientation changes, and overlapping touch targets.',
    requiredCapabilities: ['touch input mappings', 'touch-capable adapter or instrumented actions'],
    limitations: 'General desktop and browser input do not guarantee multi-touch support without explicit game instrumentation.',
    beginnerRecommendation: 'Start with one tap and one swipe action from an instrumented mobile development build.',
    directive: {
      name: 'Test mobile and touch controls',
      description: 'Try taps, long presses, swipes, virtual sticks, orientation changes, and overlapping touch controls.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['tap', 'long-press', 'swipe', 'virtual-stick', 'orientation-change', 'multi-touch'],
      avoidedActionKeywords: [],
      targetFeature: 'touch-controls',
      successConditions: ['Reported touch actions work without stuck, overlapping, or ignored controls.'],
      maxAttempts: 3,
      repeatUntilSuccess: false,
      manualSuccessConfirmation: true
    }
  },
  {
    id: 'test-resolution-and-ui-scaling',
    name: 'Test Resolution And UI Scaling',
    botProfileId: 'display-resolution-tester-bot',
    actionCount: 24,
    runtimeMinutes: 12,
    actionDelayMs: 750,
    saveScreenshots: true,
    saveStateSnapshots: false,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests common resolutions, aspect ratios, fullscreen modes, resizing, UI scale, and safe-area behavior.',
    requiredCapabilities: ['display setting actions', 'screenshot capture'],
    limitations: 'Screenshots provide evidence, but visual defects still require human or future vision-model review.',
    beginnerRecommendation: 'Use three common resolutions first and keep screenshots on before trying unusual aspect ratios.',
    directive: {
      name: 'Test resolution and UI scaling',
      description: 'Change resolution, aspect ratio, fullscreen mode, window size, and UI scale while checking for clipping or hidden controls.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['change-resolution', 'change-aspect-ratio', 'toggle-fullscreen', 'resize-window', 'change-ui-scale'],
      avoidedActionKeywords: [],
      targetFeature: 'display-ui-scaling',
      successConditions: ['UI remains usable and visible after each supported display change.'],
      maxAttempts: 3,
      repeatUntilSuccess: false,
      manualSuccessConfirmation: true
    }
  },
  {
    id: 'test-npc-navigation',
    name: 'Test NPC Navigation',
    botProfileId: 'npc-behaviour-tester-bot',
    actionCount: 35,
    runtimeMinutes: 18,
    actionDelayMs: 700,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests NPC routes, schedules, following, fleeing, blocked paths, repeated interaction, and state resets.',
    requiredCapabilities: ['NPC interactions', 'NPC position or navigation state'],
    limitations: 'Screenshot-only testing may not distinguish intended NPC waiting from broken pathfinding.',
    beginnerRecommendation: 'Choose one known NPC and one short expected route before testing schedules or many characters.',
    directive: {
      name: 'Test NPC navigation and interaction',
      description: 'Observe a known NPC route, block and reopen its path, interact repeatedly, and check following or fleeing behavior.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['find-npc', 'follow-npc', 'block-path', 'unblock-path', 'interact-npc', 'reset-npc'],
      avoidedActionKeywords: ['attack-npc'],
      targetFeature: 'npc-navigation',
      successConditions: ['The NPC follows valid routes and recovers after temporary path obstruction.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'test-boss-encounter',
    name: 'Test Boss Encounter',
    botProfileId: 'boss-encounter-tester-bot',
    actionCount: 40,
    runtimeMinutes: 20,
    actionDelayMs: 600,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'heavy',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests encounter start, combat phases, arena bounds, death and retry, completion, rewards, and skip attempts.',
    requiredCapabilities: ['combat actions', 'boss phase and encounter state', 'repeatable checkpoint or save'],
    limitations: 'Boss tests can consume significant time and should use an isolated save directly before the encounter.',
    beginnerRecommendation: 'Confirm the encounter can be restarted safely and run only one bot with one visible instance.',
    directive: {
      name: 'Test a complete boss encounter',
      description: 'Start the encounter, exercise attacks and phases, test arena boundaries, retry after death, finish, and verify rewards.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['start-boss-encounter', 'attack-boss', 'trigger-next-phase', 'test-arena-boundary', 'retry-boss', 'claim-boss-reward', 'attempt-boss-skip'],
      avoidedActionKeywords: ['leave-test-save'],
      targetFeature: 'boss-encounter',
      successConditions: ['Boss phases, retry, completion, and rewards progress without a crash or blocker.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'test-procedural-world-generation',
    name: 'Test Procedural World Generation',
    botProfileId: 'procedural-generation-tester-bot',
    actionCount: 40,
    runtimeMinutes: 20,
    actionDelayMs: 750,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'heavy',
    sessionLabel: 'Regression',
    backgroundPreferred: true,
    whatItDoes: 'Generates a small set of worlds or seeds and checks terrain, required resources, structures, and reload consistency.',
    requiredCapabilities: ['world generation or reset action', 'seed and world state'],
    limitations: 'A short focused run samples only a few seeds and cannot prove the full generation distribution.',
    beginnerRecommendation: 'Use three known test seeds, one bot, background observation, and disposable generated worlds.',
    directive: {
      name: 'Test procedural world generation',
      description: 'Generate several controlled seeds, inspect terrain and required resources, reload them, and check for unreachable or duplicated structures.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['set-world-seed', 'generate-world', 'inspect-terrain', 'check-required-resource', 'check-structure', 'reload-world'],
      avoidedActionKeywords: ['publish-world'],
      targetFeature: 'procedural-generation',
      successConditions: ['Each sampled seed generates and reloads with reachable required content.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'test-day-night-and-weather',
    name: 'Test Day/Night And Weather',
    botProfileId: 'environment-cycle-tester-bot',
    actionCount: 30,
    runtimeMinutes: 18,
    actionDelayMs: 750,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests time advancement, day and night changes, weather transitions, timed events, and save/load persistence.',
    requiredCapabilities: ['time or environment actions', 'environment state'],
    limitations: 'Real-time cycles can exceed the safe runtime unless a development build exposes time-advance actions.',
    beginnerRecommendation: 'Use a safe time-advance action and test one day-to-night transition before longer weather cycles.',
    directive: {
      name: 'Test day, night, and weather cycles',
      description: 'Advance time through day and night, trigger supported weather, watch timed events, and verify state after save and load.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['advance-time', 'set-day', 'set-night', 'change-weather', 'trigger-timed-event', 'save-game', 'load-save'],
      avoidedActionKeywords: [],
      targetFeature: 'environment-cycle',
      successConditions: ['Environment transitions complete and reported state stays consistent after save and load.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'test-loading-transitions',
    name: 'Test Loading Transitions',
    botProfileId: 'loading-transition-tester-bot',
    actionCount: 30,
    runtimeMinutes: 15,
    actionDelayMs: 750,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Tests scene changes, loading screens, fast travel, repeated transitions, cancellation, and transition failures.',
    requiredCapabilities: ['transition actions', 'scene or loading state', 'process health'],
    limitations: 'Black-box adapters may infer loading only from screenshots and responsiveness, which gives weaker timing evidence.',
    beginnerRecommendation: 'Begin with one short repeatable scene transition and confirm its normal loading time first.',
    directive: {
      name: 'Test loading and scene transitions',
      description: 'Repeat supported scene changes and fast travel, test cancellation where allowed, and watch for long or failed loading states.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['change-scene', 'fast-travel', 'start-transition', 'cancel-transition', 'reload-scene'],
      avoidedActionKeywords: [],
      targetFeature: 'loading-transitions',
      successConditions: ['Every requested transition reaches the expected scene without a crash, freeze, or excessive loading time.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'test-long-term-memory-use',
    name: 'Test Long-Term Memory Use',
    botProfileId: 'memory-leak-endurance-tester-bot',
    actionCount: 60,
    runtimeMinutes: 30,
    actionDelayMs: 750,
    saveScreenshots: true,
    saveStateSnapshots: false,
    resourceWeight: 'heavy',
    sessionLabel: 'Stress Test',
    backgroundPreferred: true,
    whatItDoes: 'Runs one bounded repeat loop while tracking memory, responsiveness, slowdown, and resource degradation.',
    requiredCapabilities: ['memory and performance measurements', 'repeatable safe actions'],
    limitations: 'Thirty minutes is only a starter endurance sample and can still use substantial CPU, RAM, logs, and disk.',
    beginnerRecommendation: 'Run one bot in the background with strict resource limits and review memory trends before extending the runtime.',
    directive: {
      name: 'Measure memory during a bounded endurance loop',
      description: 'Repeat safe gameplay and transition actions while tracking memory growth, frame degradation, and responsiveness.',
      directiveType: 'feature',
      directiveMode: 'focus',
      priority: 'normal',
      actionKeywords: ['repeat-safe-loop', 'change-scene', 'open-menu', 'close-menu', 'collect-performance-sample'],
      avoidedActionKeywords: ['quit-game', 'delete-save'],
      targetFeature: 'memory-endurance',
      successConditions: ['The bounded loop finishes without unbounded memory growth, a crash, or serious slowdown.'],
      maxAttempts: 3,
      repeatUntilSuccess: false
    }
  },
  {
    id: 'reproduce-selected-issue',
    name: 'Reproduce Selected Issue',
    botProfileId: 'sequence-breaker-bot',
    actionCount: 30,
    runtimeMinutes: 15,
    actionDelayMs: 700,
    saveScreenshots: true,
    saveStateSnapshots: true,
    resourceWeight: 'medium',
    sessionLabel: 'Regression',
    backgroundPreferred: false,
    whatItDoes: 'Creates a focused reproduction attempt using the selected issue ID and a specialist that favors unusual action sequences.',
    requiredCapabilities: ['selected issue evidence', 'actions related to the reproduction steps'],
    limitations: 'The default action words are editable starting values until the user reviews the issue actions and edits the direction.',
    beginnerRecommendation: 'Select an issue first, then replace the starting action words with its last actions before starting.',
    directive: {
      name: 'Reproduce the selected issue',
      description: 'Repeat the actions and state conditions recorded for the selected issue and capture fresh evidence if it happens again.',
      directiveType: 'issue-reproduction',
      directiveMode: 'focus',
      priority: 'high',
      actionKeywords: ['review-issue-actions', 'repeat-last-actions', 'capture-evidence'],
      avoidedActionKeywords: [],
      successConditions: ['The selected issue is detected again with fresh evidence.'],
      maxAttempts: 3,
      repeatUntilSuccess: false,
      manualSuccessConfirmation: true
    }
  }
] satisfies z.input<typeof FocusedTestTemplateSchema>[];

export const focusedTestTemplates: FocusedTestTemplate[] =
  FocusedTestTemplateSchema.array().length(15).parse(focusedTemplateInput);

export function createFocusedTestDirective(input: {
  template: FocusedTestTemplate;
  sessionId: string;
  directiveId: string;
  createdAt: string;
  selectedIssueId?: string;
}): BotTestDirective {
  const { template } = input;
  const isIssueReproduction = template.directive.directiveType === 'issue-reproduction';

  return BotTestDirectiveSchema.parse({
    directiveId: input.directiveId,
    sessionId: input.sessionId,
    name: template.directive.name,
    description: template.directive.description,
    directiveType: template.directive.directiveType as BotTestDirectiveType,
    directiveMode: template.directive.directiveMode as BotTestDirectiveMode,
    priority: template.directive.priority as BotTestDirectivePriority,
    status: 'queued',
    target: {
      allBots: false,
      botIds: [],
      profileIds: [template.botProfileId],
      gameInstanceIds: []
    },
    actionKeywords: template.directive.actionKeywords,
    avoidedActionKeywords: template.directive.avoidedActionKeywords,
    targetFeature: isIssueReproduction ? undefined : template.directive.targetFeature,
    targetIssueId: isIssueReproduction
      ? input.selectedIssueId?.trim() || 'choose-an-issue-id'
      : undefined,
    successConditions: template.directive.successConditions,
    failureConditions: [],
    steps: [],
    maxActions: template.actionCount,
    maxAttempts: template.directive.maxAttempts,
    timeoutMs: template.runtimeMinutes * 60_000,
    repeatUntilSuccess: template.directive.repeatUntilSuccess,
    manualSuccessConfirmation: template.directive.manualSuccessConfirmation,
    createdAt: input.createdAt,
    createdBy: 'focused-test-template',
    notes: `Focused template: ${template.id}`
  });
}
